# Generated by Django 5.1.3 on 2024-11-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_merge_20241114_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='appUserID',
        ),
        migrations.AlterField(
            model_name='dealership',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='rentoid',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
