openapi: 3.0.3
info:
  title: EasyRent API
  version: 0.0.0
paths:
  /api/auth/loginUser/:
    post:
      operationId: api_auth_loginUser_create
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/logoutUser/:
    post:
      operationId: api_auth_logoutUser_create
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/registerCompany/:
    post:
      operationId: api_auth_registerCompany_create
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/registerUser/:
    post:
      operationId: api_auth_registerUser_create
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/home/offer/{offer_id}/:
    get:
      operationId: api_home_offer_retrieve
      parameters:
      - in: path
        name: offer_id
        schema:
          type: string
        required: true
      tags:
      - home
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferDetails'
          description: ''
        '404':
          description: Offer Not Found
  /api/home/showcased/:
    get:
      operationId: api_home_showcased_retrieve
      tags:
      - home
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /money/wallet/addAccount/:
    post:
      operationId: money_wallet_addAccount_create
      tags:
      - wallet
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: Wallet successfully created
        '400':
          description: Bad Request
  /money/wallet/addMoney/{wallid}/:
    post:
      operationId: money_wallet_addMoney_create
      parameters:
      - in: path
        name: wallid
        schema:
          type: string
        required: true
      tags:
      - wallet
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: Money added successfully
        '400':
          description: Bad Request
  /money/wallet/removeMoney/{wallid}/:
    post:
      operationId: money_wallet_removeMoney_create
      parameters:
      - in: path
        name: wallid
        schema:
          type: string
        required: true
      tags:
      - wallet
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: Money removed successfully
        '400':
          description: Bad Request
components:
  schemas:
    OfferDetails:
      type: object
      properties:
        image:
          type: string
          default: base64
        makeName:
          type: string
        modelName:
          type: string
        companyName:
          type: string
        dealership_id:
          type: integer
        noOfSeats:
          type: integer
        modelType:
          type: string
        automatic:
          type: boolean
        price:
          type: number
          format: double
          default: 0.1
        rating:
          type: number
          format: double
          default: 0.1
        noOfReviews:
          type: integer
        companyLogo:
          type: string
          default: base64
        description:
          type: string
        canReview:
          type: integer
      required:
      - automatic
      - canReview
      - companyName
      - dealership_id
      - description
      - makeName
      - modelName
      - modelType
      - noOfReviews
      - noOfSeats
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
