# Generated by Django 5.1.2 on 2024-11-11 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('UID', models.CharField(max_length=16)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('passwordHash', models.CharField(max_length=255)),
                ('isActivated', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('appUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(max_length=100)),
                ('streetNo', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('isHQ', models.BooleanField(blank=True, default=False)),
                ('cityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.city')),
                ('dealershipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('generationTimestamp', models.DateTimeField(auto_now_add=True)),
                ('isComplete', models.BooleanField(blank=True, default=False)),
                ('appUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Rentoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('appUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTheWeek', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('isHQ', True)), fields=('dealershipID', 'isHQ'), name='unique_hq_per_dealership'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('cityID', 'streetName', 'streetNo'), ('latitude', 'longitude')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('locationID', 'dayOfTheWeek')},
        ),
    ]
