# Generated by Django 5.1.3 on 2025-01-15 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('dealership_id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(blank=True, max_length=20, null=True)),
                ('TIN', models.CharField(default=None, max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='logos')),
                ('isAccepted', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(blank=True, default='', max_length=50)),
                ('cityName', models.CharField(blank=True, default='', max_length=50)),
                ('streetName', models.CharField(max_length=100)),
                ('streetNo', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('isHQ', models.BooleanField(blank=True, default=False)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='Rentoid',
            fields=[
                ('rentoid_id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(blank=True, max_length=20, null=True)),
                ('driversLicenseNo', models.CharField(default=None, max_length=16)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('workingHours_id', models.AutoField(primary_key=True, serialize=False)),
                ('dayOfTheWeek', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('isHQ', True)), fields=('dealership', 'isHQ'), name='unique_hq_per_dealership'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('countryName', 'cityName', 'streetName', 'streetNo'), ('latitude', 'longitude')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('location', 'dayOfTheWeek')},
        ),
    ]
