# Generated by Django 5.1.3 on 2025-01-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentoid',
            name='balance',
        ),
    ]
