# Generated by Django 5.1.3 on 2024-11-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dealership',
            name='picturePath',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='appUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser', unique=True),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='companyName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rentoid',
            name='appUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser', unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='countryID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='src.country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('cityName', 'countryID')},
        ),
    ]
