# Generated by Django 5.1.3 on 2025-01-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='image',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
