# Generated by Django 5.1.3 on 2025-01-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_dealership_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.location'),
        ),
    ]
