# Generated by Django 5.1.3 on 2024-11-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_country_dealership_picturepath_alter_city_cityname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='appUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser'),
        ),
        migrations.AlterField(
            model_name='rentoid',
            name='appUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser'),
        ),
    ]
