# Generated by Django 5.1.3 on 2024-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_dealership_appuserid_alter_rentoid_appuserid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='picturePath',
        ),
        migrations.AddField(
            model_name='dealership',
            name='image',
            field=models.BinaryField(default=b''),
        ),
    ]
