# Generated by Django 5.1.3 on 2024-11-12 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_dealership_picturepath_dealership_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='appUserID',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='appUserID',
        ),
        migrations.RemoveField(
            model_name='rentoid',
            name='appUserID',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_hq_per_dealership',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='countryID',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='cityID',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='dealershipID',
            new_name='dealership',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='locationID',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='rentoid',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='rentoid',
            name='lastName',
        ),
        migrations.AddField(
            model_name='dealership',
            name='TIN',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='dealership',
            name='isAccepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dealership',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dealership',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentoid',
            name='driversLicenseNumber',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='rentoid',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentoid',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('cityName', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'streetName', 'streetNo'), ('latitude', 'longitude')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('location', 'dayOfTheWeek')},
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('isHQ', True)), fields=('dealership', 'isHQ'), name='unique_hq_per_dealership'),
        ),
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
