# Generated by Django 5.1.3 on 2024-11-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_dealership_appuserid'),
        ('src', '0005_remove_registrationrequest_appuserid_and_more'),
    ]

    operations = [
    ]
