# Generated by Django 5.1.3 on 2025-01-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('gems', models.IntegerField(default=0)),
                ('rentoid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.rentoid')),
            ],
        ),
    ]
