# Generated by Django 5.1.3 on 2025-01-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_rentoid_balance'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='rentoid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.rentoid'),
        ),
    ]
