# Generated by Django 5.1.2 on 2025-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="insured",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="yearOfCreation",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="isVisible",
            field=models.BooleanField(default=True),
        ),
    ]
