# Generated by Django 5.1.3 on 2024-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='picture',
        ),
        migrations.AddField(
            model_name='offer',
            name='picturePath',
            field=models.CharField(default='', max_length=50),
        ),
    ]
