# Generated by Django 5.1.3 on 2025-01-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rent_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='noOfReviews',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='dateTimeReturned',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rent', unique=True),
        ),
    ]
