# Generated by Django 5.1.3 on 2024-11-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_offer_picturepath_offer_image'),
        ('src', '0005_remove_registrationrequest_appuserid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='dealerID',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='modelID',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='dealerID',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modelID',
            new_name='model',
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('model', 'dealer')},
        ),
    ]
