# Generated by Django 5.1.3 on 2025-01-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vehicle_noofreviews_vehicle_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.rent'),
        ),
    ]
