# Generated by Django 5.1.3 on 2025-01-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_review_rent'),
        ('src', '0002_alter_dealership_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rentedLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_location', to='src.location'),
        ),
        migrations.AddField(
            model_name='rent',
            name='returnLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_location', to='src.location'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='offers'),
        ),
    ]
