# Generated by Django 5.1.3 on 2025-01-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rent_rentedlocation_rent_returnlocation_and_more'),
        ('src', '0003_alter_workinghours_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='dealer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.dealership'),
        ),
        migrations.AlterField(
            model_name='model',
            name='modelType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.modeltype'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rentoid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.rentoid'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.model'),
        ),
    ]
